spring:
  datasource:
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/postgres
      username: checker
      password: 123456
server:
  port: 8081
